name: Test

on: [push, pull_request]

jobs:

  test:
    runs-on: ubuntu-18.04

    strategy:
      fail-fast: false
      matrix:
        racket-version: ['7.9', '8.4', 'current']

    steps:
    - uses: actions/checkout@v2
    - uses: Bogdanp/setup-racket@v1.7
      with:
          architecture: 'x64'
          distribution: 'full'
          variant: 'CS'
          version: ${{ matrix.racket-version }}
    - run: raco pkg install --auto --link $PWD
    - run: raco test -c bv

